services:
  web:
    build: .
    container_name: mcu_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: always

  db:
    image: mysql:8.1
    container_name: mcu_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: miagecinemauniverse
      MYSQL_USER: mcu
      MYSQL_PASSWORD: mcu
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mcu_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    volumes:
      - ./phpmyadmin_apache.conf:/etc/apache2/sites-available/000-default.conf:ro

volumes:
  db_data:
